<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ftp_app_description'] = 'FTP-сервер предоставляет возможность управление файлами и их хранение, используя стандартные протоколы FTP и безопасные протоколы FTP';
$lang['ftp_app_name'] = 'FTP Сервер';
$lang['ftp_flexshare_port'] = 'Flexshare Порт';
$lang['ftp_home_share_port'] = 'Домашний общедоступный порт';
$lang['ftp_max_instances'] = 'Максимум ссылок';
$lang['ftp_maximum_instances_invalid'] = 'Максимальные ссылки недействительны.';
$lang['ftp_port_reserved_for_flexshare'] = 'Порт зарезервирован для Flexshare.';
$lang['ftp_server_name'] = 'Имя сервера';
$lang['ftp_server_name_invalid'] = 'Имя сервера недействителено.';
