#!/bin/sh

# Set DefaultAddress to avoid issue with unresolvable hostname (tracker #507)
#----------------------------------------------------------------------------

CHECK=`grep ^DefaultAddress /etc/proftpd.conf 2>/dev/null`

if [ -z "$CHECK" ]; then
    logger -p local6.notice -t installer "app-ftp-core - adding default address to configuration"
    echo "DefaultAddress 127.0.0.1" >> /etc/proftpd.conf
fi

# FIXME: 6.2.0 beta/rc upgrade. Remove after final
CHECK=`grep "^Port[[:space:]]*21$" /etc/proftpd.conf`

if [ -n "$CHECK" ]; then
    sed -i -e 's/^Port[[:space:]]*21/Port 2121/' /etc/proftpd.conf 
fi

exit 0
