#!/bin/sh

# Set DefaultAddress to avoid issue with unresolvable hostname (tracker #507)
#----------------------------------------------------------------------------

CHECK=`grep ^DefaultAddress /etc/proftpd.conf 2>/dev/null`

if [ -z "$CHECK" ]; then
    logger -p local6.notice -t installer "app-ftp-core - adding default address to configuration"
    echo "DefaultAddress 127.0.0.1" >> /etc/proftpd.conf
fi

# PAM check
#----------

CHECK=`grep clearos/ftp.d /etc/pam.d/proftpd`
if [ -z "$CHECK" ]; then
    logger -p local6.notice -t installer "app-ftp-core - applying IMAP PAM configuration"
    [ -e /etc/pam.d/proftpd ] && cp /etc/pam.d/proftpd /var/clearos/ftp/backup/proftpd.pam.$TIMESTAMP
    cp /usr/clearos/apps/ftp/deploy/proftpd.pam /etc/pam.d/proftpd
fi

CHECK=`grep pam_shells.so /etc/pam.d/proftpd`
if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-ftp-core - resetting pam_shells PAM configuration"
    sed -i -e 's/pam_shells.so/pam_nologin.so/' /etc/pam.d/proftpd
fi

# Run syncaction on upgrades
#---------------------------

/usr/clearos/apps/ftp/deploy/syncaction

# FIXME: 6.2.0 beta/rc upgrade. Remove after final
CHECK=`grep "^Port[[:space:]]*21$" /etc/proftpd.conf`

if [ -n "$CHECK" ]; then
    sed -i -e 's/^Port[[:space:]]*21/Port 2121/' /etc/proftpd.conf 
fi

exit 0
