<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['ftp_app_description'] = 'Serwer FTP umożliwia zarządzanie plikami oraz magazynem danych używając standardowych protokołów FTP oraz bezpiecznego FTP.';
$lang['ftp_app_name'] = 'Serwer FTP';
$lang['ftp_flexshare_port'] = 'Port Flexshare';
$lang['ftp_home_share_port'] = 'Współdzielony port domowy';
$lang['ftp_max_instances'] = 'Maksymalna liczna instancji';
$lang['ftp_maximum_instances_invalid'] = 'Maksymalna liczba instancji jest nieprawidłowa.';
$lang['ftp_port_reserved_for_flexshare'] = 'Ten port zarezerwowany jest dla Flexshare.';
$lang['ftp_server_name'] = 'Nazwa serwera';
$lang['ftp_server_name_invalid'] = 'Nazwa serwera jest nieprawidłowa.';
